### ISSUE TITLE
Test result trend graph

### ISSUE THREAD

**Issue by humbled** [jenkinsci/cucumber-reports-plugin#17] opened 2016-01-17 20:56 UTC
The only way to view the results of tests over time is to skip between different builds. Would be great to have a trend graph like jenkins provides for unit test trends. I will look to provide something

**Comment by damianszczepanik** [comment] 2016-01-17 21:06
Duplicate of damianszczepanik/cucumber-reporting/issues/33

**Closed by damianszczepanik** 2016-01-17 21:06 UTC

**Comment by humbled** [comment] 2016-01-17 21:44
Cheers. Which project is the master? Which issues list?
