### ISSUE TITLE
Report Graph shows "This content requires JavaScript"

### ISSUE THREAD

**Issue by rahullodha85** [jenkinsci/cucumber-reports-plugin#9] opened 2015-12-28 22:36 UTC
I recently upgraded cucmber reports plugin to version 1.0.0, and now i see "This content requires JavaScript" instead of actual graph.
 
Please help with a fix or a workaround.
Thank You!

Attached here is browser log
[browser log.txt](https://github.com/jenkinsci/cucumber-reports-plugin/files/73596/browser.log.txt)

**Comment by djwgit** [comment] 2015-12-29 00:45
got the same issue, after upgrading to jenkins 1.643 and plugin 1.0.0
downgrade to jenkins 1.638 and plugin 0.1, still same issue with the report.

**Comment by rahullodha85** [comment] 2015-12-29 15:16
@djwgit I am running jenkins as a service so i had to run System.setProperty("hudson.model.DirectoryBrowserSupport.CSP", "") from jenkins script console. but javascript error did not occur after setting this flag to empty string.
Thank you for your help :)

**Comment by damianszczepanik** [comment] 2015-12-30 21:28
Duplicate of jenkinsci/cucumber-reports-plugin/issues/7

**Closed by damianszczepanik** 2015-12-30 21:28 UTC

**Comment by enggabhishekshinde** [comment] 2016-02-11 11:25
Please do following steps to fix it.

Add or modify following parameter in /etc/sysconfig/jenkins file..

JENKINS_JAVA_OPTIONS=" -Djava.awt.headless=true **-Dhudson.model.DirectoryBrowserSupport.CSP=\"\"** "

**Comment by damianszczepanik** [comment] 2016-02-11 18:46
No need to, recent release fixes this problem

**Comment by TeresaP** [comment] 2016-06-20 21:02
We just updated Jenkins and our plug-in was severely out of date, so we updated it to 2.5.0. Now, when we view our reports, we see the above error: `This content requires JavaScript`. I have tried editing our jenkins-runner.sh file's javaArgs to ```javaArgs=" -Djava.awt.headless=true -Dhudson.model.DirectoryBrowserSupport.CSP=\"\" "``` without luck. Is this still a recommended workaround?

**Comment by enggabhishekshinde** [comment] 2016-06-21 02:41
HI TerasaP,

Please let me know which Jenkins version you are using. Also please check java process on jenkins server whether it's contain CSP flag or not.

Regards,
Abhishek.

**Comment by enggabhishekshinde** [comment] 2016-06-21 02:42
HI TeresaP,

Please let me know which Jenkins version you are using. Also please check java process on jenkins server whether it's contain CSP flag or not.

Regards,
Abhishek.

**Comment by damianszczepanik** [comment] 2016-06-21 18:22
New version has been published, please upgrade
