### ISSUE TITLE
is it possible to move the background steps to the scenario itself and get rid of background section in the report? 

### ISSUE THREAD

**Issue by cbarath1986** [jenkinsci/cucumber-reports-plugin#307] opened 2019-03-12 18:06 UTC
is it possible to move the background steps to the scenario itself and get rid of background section in the report?  i use cucumber with java and testng and implemented latest version of net.masterthought cucumber report. My business users wanted to have all the steps related to background at the top of scenario steps as its confusing them if they execute multiple test scenarios in feature file.

The hierarchy in the report right now is

| Background
| scenario
| Background
| Scenario

so they want the steps from BG to be included into scenario steps in right hierarchy. Is it possible to do with current version?

or i have only option which is edit the json file to have these change which is kind of tedious. PLease let me know. Thank you!

**Comment by damianszczepanik** [comment] 2019-03-12 21:54
Duplicate of https://github.com/damianszczepanik/cucumber-reporting/issues/815

**Closed by damianszczepanik** 2019-03-12 21:54 UTC
