### ISSUE TITLE
Feature Request: Want 2 JVM reports - one for 1st run, and one for 2nd run

### ISSUE THREAD

**Issue by JasonSmiley208** [jenkinsci/cucumber-reports-plugin#84] opened 2016-08-31 20:15 UTC
**Context:**
   As an SDET, I want to run tests twice.
   The 1st run of tests will run the entire test suite - generates a .json report at path "A:
   The 2nd run of tests will run all tests which failed during the 1st run (if applicable) - also generates a .json report at path "B"

**Problem:**
  There is no way to generate 2 separate JVM reports. Instead, the only option is to provide both .json files as input for the jvm report. Additionally, I can only create a single Cucumber-JVM report post build action per job

**Proposed Solution:**
  Option 1 - Make it so the plugin could be added to the Jenkins Job multiple times and make the report link editable (can say which report it is). 1st report would look at the 1st run data and 2nd report would look at the rerun data.
  Option 2 - Give the plugin an option to "generate multiple reports" which would allow me to add the paths to the .json files for each report. 1st report uses path "A", and 2nd report uses path "B". These reports should be name-able

**Comment by damianszczepanik** [comment] 2016-08-31 20:43
Duplicate of #81

**Closed by damianszczepanik** 2016-08-31 20:43 UTC

**Comment by shchukax** [comment] 2020-02-03 21:34
I know this issue is closed, but I submitted a PR to enable multiple publishing multiple reports from the same job.
