### ISSUE TITLE
Jenkins not being able to connect to plugin data after moving directory

### ISSUE THREAD

**Issue by rc-ck** [jenkinsci/cucumber-reports-plugin#132] opened 2017-03-13 10:52 UTC
Hi there

I was running Jenkins with Cucumber Reports natively on init.d. After moving to systemd it was required to move Jenkins files from /var/lib/jenkins to var/lib/jenkins/.jenkins in order for it to work. Generally speaking things went smoothly and everything works. Everything but Cucumber plugin data. 

Now when I view some job via web interface and try viewing "Cucumber reports" I get an error saying the browser was not able to find page ipAddress/someJobs/cucumber-html-reports/overview-features.html.

I believe the case here is rather trivial, but I cannot find the setting to show the plugin the new and proper directory for the data (all of the data is there on the partition). Where should I look for the setting file? Or maybe this is not the case here?

**Comment by damianszczepanik** [comment] 2017-03-13 12:38
Show me Jenkins build log

**Comment by rc-ck** [comment] 2017-03-15 09:28
Here's the log from a build completed before moving to systemd:

`[Pipeline] step
[CucumberReport] Preparing Cucumber Reports
[CucumberReport] Copied 15 json files from workspace "/var/lib/jenkins/workspace/key_key-key_master-someID/build/tests/json" to reports directory "/var/lib/jenkins/jobs/key/jobs/key-key/branches/master/builds/id/cucumber-html-reports/.cache"
[CucumberReport] Filtered out 15 json files:
[CucumberReport] /var/lib/jenkins/jobs/key/jobs/key-key/branches/master/builds/id/cucumber-html-reports/.cache/report001/report.json
[CucumberReport] /var/lib/jenkins/jobs/key/jobs/key-key/branches/master/builds/id/cucumber-html-reports/.cache/report002/report.json
[CucumberReport] /var/lib/jenkins/jobs/key/jobs/key-key/branches/master/builds/id/cucumber-html-reports/.cache/report003/report.json
[CucumberReport] /var/lib/jenkins/jobs/key/jobs/key-key/branches/master/builds/id/cucumber-html-reports/.cache/report004/report.json
[CucumberReport] /var/lib/jenkins/jobs/key/jobs/key-key/branches/master/builds/id/cucumber-html-reports/.cache/report005/report.json
[CucumberReport] /var/lib/jenkins/jobs/key/jobs/key-key/branches/master/builds/id/cucumber-html-reports/.cache/report006/report.json
[CucumberReport] /var/lib/jenkins/jobs/key/jobs/key-key/branches/master/builds/id/cucumber-html-reports/.cache/report007/report.json
[CucumberReport] /var/lib/jenkins/jobs/key/jobs/key-key/branches/master/builds/id/cucumber-html-reports/.cache/report008/report.json
[CucumberReport] /var/lib/jenkins/jobs/key/jobs/key-key/branches/master/builds/id/cucumber-html-reports/.cache/report009/report.json
[CucumberReport] /var/lib/jenkins/jobs/key/jobs/key-key/branches/master/builds/id/cucumber-html-reports/.cache/report010/report.json
[CucumberReport] /var/lib/jenkins/jobs/key/jobs/key-key/branches/master/builds/id/cucumber-html-reports/.cache/report011/report.json
[CucumberReport] /var/lib/jenkins/jobs/key/jobs/key-key/branches/master/builds/id/cucumber-html-reports/.cache/report012/report.json
[CucumberReport] /var/lib/jenkins/jobs/key/jobs/key-key/branches/master/builds/id/cucumber-html-reports/.cache/report013/report.json
[CucumberReport] /var/lib/jenkins/jobs/key/jobs/key-key/branches/master/builds/id/cucumber-html-reports/.cache/report014/report.json
[CucumberReport] /var/lib/jenkins/jobs/key/jobs/key-key/branches/master/builds/id/cucumber-html-reports/.cache/report015/report.json
[CucumberReport] Found 20 failed steps, while expected not more than 0
[CucumberReport] Build status is left unchanged
[Pipeline] step`

And here's the log from a build completed after moving to systemd:

`[Pipeline] step
[CucumberReport] Preparing Cucumber Reports
[CucumberReport] Copied 14 json files from workspace "/var/lib/jenkins/.jenkins/workspace/key_key-key_master-someID/build/tests/json" to reports directory "/var/lib/jenkins/.jenkins/jobs/key/jobs/key-key/branches/master/builds/id/cucumber-html-reports/.cache"
[CucumberReport] Filtered out 14 json files:
[CucumberReport] /var/lib/jenkins/.jenkins/jobs/key/jobs/key-key/branches/master/builds/id/cucumber-html-reports/.cache/report001/report.json
[CucumberReport] /var/lib/jenkins/.jenkins/jobs/key/jobs/key-key/branches/master/builds/id/cucumber-html-reports/.cache/report002/report.json
[CucumberReport] /var/lib/jenkins/.jenkins/jobs/key/jobs/key-key/branches/master/builds/id/cucumber-html-reports/.cache/report003/report.json
[CucumberReport] /var/lib/jenkins/.jenkins/jobs/key/jobs/key-key/branches/master/builds/id/cucumber-html-reports/.cache/report004/report.json
[CucumberReport] /var/lib/jenkins/.jenkins/jobs/key/jobs/key-key/branches/master/builds/id/cucumber-html-reports/.cache/report005/report.json
[CucumberReport] /var/lib/jenkins/.jenkins/jobs/key/jobs/key-key/branches/master/builds/id/cucumber-html-reports/.cache/report006/report.json
[CucumberReport] /var/lib/jenkins/.jenkins/jobs/key/jobs/key-key/branches/master/builds/id/cucumber-html-reports/.cache/report007/report.json
[CucumberReport] /var/lib/jenkins/.jenkins/jobs/key/jobs/key-key/branches/master/builds/id/cucumber-html-reports/.cache/report008/report.json
[CucumberReport] /var/lib/jenkins/.jenkins/jobs/key/jobs/key-key/branches/master/builds/id/cucumber-html-reports/.cache/report009/report.json
[CucumberReport] /var/lib/jenkins/.jenkins/jobs/key/jobs/key-key/branches/master/builds/id/cucumber-html-reports/.cache/report010/report.json
[CucumberReport] /var/lib/jenkins/.jenkins/jobs/key/jobs/key-key/branches/master/builds/id/cucumber-html-reports/.cache/report011/report.json
[CucumberReport] /var/lib/jenkins/.jenkins/jobs/key/jobs/key-key/branches/master/builds/id/cucumber-html-reports/.cache/report012/report.json
[CucumberReport] /var/lib/jenkins/.jenkins/jobs/key/jobs/key-key/branches/master/builds/id/cucumber-html-reports/.cache/report013/report.json
[CucumberReport] /var/lib/jenkins/.jenkins/jobs/key/jobs/key-key/branches/master/builds/id/cucumber-html-reports/.cache/report014/report.json
[Pipeline] step`

The old build log is not accessible via www interface. The new one is.

After creating a symlink that redirects to /var/lib/jenkins/.jenkins/jobs anything that's looking for /var/lib/jenkins/jobs/, old build logs are also accessible via www. But I don't find this solution very elegant. 
What could be done here in order to make everything work without workarounds such as symlink?

**Comment by damianszczepanik** [comment] 2017-03-16 21:15
Duplicate of #81

**Closed by damianszczepanik** 2017-03-16 21:15 UTC
