### ISSUE TITLE
Friendly report url when using title

### ISSUE THREAD

**Issue by thiagotrentin** [jenkinsci/cucumber-reports-plugin#373] opened 2020-08-22 20:05 UTC
When publishing cucumber reports report url is something like this:
**http://domain/job/job_name/build_number/cucumber-html-reports/overview-features.html**

But when a report title is defined it turns into something like this:
**http://domain/job/job_name/build_number/cucumber-html-reports_0fa5f03a-2fe5-3a42-9187-527e86f47de5/overview-features.html**

The URL is not so friendly for those who will access the report, in addition to making it difficult to access the report in some automated way.

Could you please consider changing it for something like this?
**http://domain/job/job_name/build_number/cucumber-html-reports_report-title/overview-features.html**

**Comment by damianszczepanik** [comment] 2020-08-30 19:51
This is feature

Duplicate of #372

**Closed by damianszczepanik** 2020-08-30 19:51 UTC
