### ISSUE TITLE
cannot display the cucumber reports 

### ISSUE THREAD

**Issue by rlagoue** [jenkinsci/cucumber-reports-plugin#68] opened 2016-07-25 09:05 UTC
Hello,

after upgrading to version 2.6.2 the link to the cucumber reports html file no more works. It redirects me to build page. I tried 2.6.3 without success. Now I am look how to downgrade to 2.5.1

cheers

**Comment by rlagoue** [comment] 2016-07-25 09:19
I just ran the build again, and the reports (with version 2.6.3) of the last build are displayed. But the reports of the builds executex before are not

**Comment by damianszczepanik** [comment] 2016-07-25 18:38
Duplicate of damianszczepanik/cucumber-reporting-jenkins/issues/162

**Closed by damianszczepanik** 2016-07-25 18:38 UTC
