### ISSUE TITLE
Trends for Feature/Scenario Duration

### ISSUE THREAD

**Issue by biagiolampo** [jenkinsci/cucumber-reports-plugin#130] opened 2017-03-11 08:40 UTC
Hi,
it would be very useful to have on jenkins the trends for Feature/Scenario duration.
This could help on having a benchmarking for each Feature/Scenario.
The reason of having this is especially related to products where there are some Performance KPI to be secured.

Thanks
Biagio

**Comment by damianszczepanik** [comment] 2017-03-11 22:47
Duplicate of https://github.com/damianszczepanik/cucumber-reporting/issues/609

**Closed by damianszczepanik** 2017-03-11 22:47 UTC
