### ISSUE TITLE
Broken formatting 

### ISSUE THREAD

**Issue by roman-grytsay** [jenkinsci/cucumber-reports-plugin#15] opened 2016-01-15 16:11 UTC
Jenkins ver. 1.644
Plugin ver. 1.1.0
All pages: feature view, tag view, overview...
Please see the attachment.
![cucumber](https://cloud.githubusercontent.com/assets/8222971/12357919/03367b98-bbab-11e5-9408-f7446197d3c8.png)

**Comment by damianszczepanik** [comment] 2016-01-15 20:27
Duplicate of jenkinsci/cucumber-reports-plugin/issues/7

**Closed by damianszczepanik** 2016-01-15 20:27 UTC
