### ISSUE TITLE
Filename too long after plugin upgrade

### ISSUE THREAD

**Issue by adilfulara** [jenkinsci/cucumber-reports-plugin#101] opened 2016-12-02 07:49 UTC
Old Version: 0.0.23
New Version: 3.2.0

Using the old plugin, html reports were generated correctly ( multiple json files )
After upgrade to the above mentioned version,

we see `filename too long version`

stack trace

```net.masterthought.cucumber.ValidationException: java.io.FileNotFoundException: /var/lib/jenkins/jobs/tm__ccp-jenkins-automation-test-master-wiremock/configurations/axis-domain/tm_us/axis-jdk/JDK-AT/axis-label/AT-master/axis-platform/desktop/builds/53/cucumber-html-reports/report-feature_-var-lib-jenkins-workspace-tm__ccp-jenkins-automation-test-master-wiremock-domain-tm_us-jdk-JDK-AT-label-AT-master-platform-desktop-tmol-automation-tests-src-test-resources-features_tm_us-edp-exposefilters-ModalCheckboxFiltering-feature_6.html (File name too long)
	at net.masterthought.cucumber.generators.AbstractPage.generateReport(AbstractPage.java:72)
	at net.masterthought.cucumber.generators.AbstractPage.generatePage(AbstractPage.java:55)
	at net.masterthought.cucumber.ReportBuilder.generatePages(ReportBuilder.java:147)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:80)
	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:130)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:80)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:75)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:726)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:671)
	at hudson.model.Run.execute(Run.java:1766)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:408)
Caused by: java.io.FileNotFoundException: /var/lib/jenkins/jobs/tm__ccp-jenkins-automation-test-master-wiremock/configurations/axis-domain/tm_us/axis-jdk/JDK-AT/axis-label/AT-master/axis-platform/desktop/builds/53/cucumber-html-reports/report-feature_-var-lib-jenkins-workspace-tm__ccp-jenkins-automation-test-master-wiremock-domain-tm_us-jdk-JDK-AT-label-AT-master-platform-desktop-tmol-automation-tests-src-test-resources-features_tm_us-edp-exposefilters-ModalCheckboxFiltering-feature_6.html (File name too long)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.(FileOutputStream.java:221)
	at java.io.FileOutputStream.(FileOutputStream.java:171)
	at net.masterthought.cucumber.generators.AbstractPage.generateReport(AbstractPage.java:69)
	... 15 more
```

Trying to generate report from following files. Make sure they are valid cucumber report files:
```
/var/lib/jenkins/jobs/tm__ccp-jenkins-automation-test-master-wiremock/configurations/axis-domain/tm_us/axis-jdk/JDK-AT/axis-label/AT-master/axis-platform/desktop/builds/53/1.json
           /var/lib/jenkins/jobs/tm__ccp-jenkins-automation-test-master-wiremock/configurations/axis-domain/tm_us/axis-jdk/JDK-AT/axis-label/AT-master/axis-platform/desktop/builds/53/10.json
           /var/lib/jenkins/jobs/tm__ccp-jenkins-automation-test-master-wiremock/configurations/axis-domain/tm_us/axis-jdk/JDK-AT/axis-label/AT-master/axis-platform/desktop/builds/53/11.json
           /var/lib/jenkins/jobs/tm__ccp-jenkins-automation-test-master-wiremock/configurations/axis-domain/tm_us/axis-jdk/JDK-AT/axis-label/AT-master/axis-platform/desktop/builds/53/12.json
           /var/lib/jenkins/jobs/tm__ccp-jenkins-automation-test-master-wiremock/configurations/axis-domain/tm_us/axis-jdk/JDK-AT/axis-label/AT-master/axis-platform/desktop/builds/53/13.json
           /var/lib/jenkins/jobs/tm__ccp-jenkins-automation-test-master-wiremock/configurations/axis-domain/tm_us/axis-jdk/JDK-AT/axis-label/AT-master/axis-platform/desktop/builds/53/14.json
           /var/lib/jenkins/jobs/tm__ccp-jenkins-automation-test-master-wiremock/configurations/axis-domain/tm_us/axis-jdk/JDK-AT/axis-label/AT-master/axis-platform/desktop/builds/53/15.json
           /var/lib/jenkins/jobs/tm__ccp-jenkins-automation-test-master-wiremock/configurations/axis-domain/tm_us/axis-jdk/JDK-AT/axis-label/AT-master/axis-platform/desktop/builds/53/16.json
           /var/lib/jenkins/jobs/tm__ccp-jenkins-automation-test-master-wiremock/configurations/axis-domain/tm_us/axis-jdk/JDK-AT/axis-label/AT-master/axis-platform/desktop/builds/53/17.json
           /var/lib/jenkins/jobs/tm__ccp-jenkins-automation-test-master-wiremock/configurations/axis-domain/tm_us/axis-jdk/JDK-AT/axis-label/AT-master/axis-platform/desktop/builds/53/2.json
           /var/lib/jenkins/jobs/tm__ccp-jenkins-automation-test-master-wiremock/configurations/axis-domain/tm_us/axis-jdk/JDK-AT/axis-label/AT-master/axis-platform/desktop/builds/53/3.json
           /var/lib/jenkins/jobs/tm__ccp-jenkins-automation-test-master-wiremock/configurations/axis-domain/tm_us/axis-jdk/JDK-AT/axis-label/AT-master/axis-platform/desktop/builds/53/4.json
           /var/lib/jenkins/jobs/tm__ccp-jenkins-automation-test-master-wiremock/configurations/axis-domain/tm_us/axis-jdk/JDK-AT/axis-label/AT-master/axis-platform/desktop/builds/53/5.json
           /var/lib/jenkins/jobs/tm__ccp-jenkins-automation-test-master-wiremock/configurations/axis-domain/tm_us/axis-jdk/JDK-AT/axis-label/AT-master/axis-platform/desktop/builds/53/6.json
           /var/lib/jenkins/jobs/tm__ccp-jenkins-automation-test-master-wiremock/configurations/axis-domain/tm_us/axis-jdk/JDK-AT/axis-label/AT-master/axis-platform/desktop/builds/53/7.json
           /var/lib/jenkins/jobs/tm__ccp-jenkins-automation-test-master-wiremock/configurations/axis-domain/tm_us/axis-jdk/JDK-AT/axis-label/AT-master/axis-platform/desktop/builds/53/8.json
           /var/lib/jenkins/jobs/tm__ccp-jenkins-automation-test-master-wiremock/configurations/axis-domain/tm_us/axis-jdk/JDK-AT/axis-label/AT-master/axis-platform/desktop/builds/53/9.json
                  
```

The job is multi module job with 2 axis.

Any pointers on how to resolve this issue other than downgrading ?

Thank you

**Comment by damianszczepanik** [comment] 2016-12-03 19:38
Duplicate of damianszczepanik/maven-cucumber-reporting/issues/53

**Closed by damianszczepanik** 2016-12-03 19:38 UTC

**Comment by adilfulara** [comment] 2016-12-03 22:22
The issue you point to is for Windows and we use Linux. Does the plugin generate the filename or is it something that the Jenkins runner does that? I could take a look and attempt to fix if you could point me in the correct direction. 

Thank you

**Comment by damianszczepanik** [comment] 2016-12-03 23:28
Well, Linux has very, very long limit for the file name length and I believe report cannot reach such limit. Name of the file is generated from feature ID. And the ID comes from feature name. So If you have very long feature name and use it as description then the problem may occur otherwise rather not.

**Comment by adilfulara** [comment] 2016-12-04 00:42
the name of the feature is `EDP - Expose Filters` 
while the name of the file from above is `cucumber-html-reports/report-feature_-var-lib-jenkins-workspace-tm__ccp-jenkins-automation-test-master-wiremock-domain-tm_us-jdk-JDK-AT-label-AT-master-platform-desktop-tmol-automation-tests-src-test-resources-features_tm_us-edp-exposefilters-ModalCheckboxFiltering-feature_6.html` which is why i was wondering who is creating the additional pre-text?

**Comment by damianszczepanik** [comment] 2016-12-04 15:08
I was wrong, the file name is based on the URI https://github.com/damianszczepanik/cucumber-reporting/blob/master/src/main/java/net/masterthought/cucumber/json/Feature.java#L189 and this is created by cucumber implementation from (I think so)j feature file name and its location.

Another problem is that when I change the file name I loose report compatibility - when you select Previous report then you gets 404 if the file is changed

**Comment by mattiasmgn** [comment] 2017-11-08 08:42
We ran in to this problem too. On our Linux system the limit is 256 for file name length. The filename generated by Feature.calculateReportFileName needs a fix to ensure file name does not exceed 256 characters.

**Comment by dogloblin** [comment] 2018-11-14 16:37
So, any solution for this? Why does it create a file name with all of the subdirectories added to it?

**Comment by damianszczepanik** [comment] 2018-11-15 21:54
It gets the file name from uri. I will fix it with next version

**Comment by dogloblin** [comment] 2018-11-26 16:19
Thank you! We will pick it when the next version is available. Currently running 4.2.2 on Jenkins...

**Comment by damianszczepanik** [comment] 2018-11-26 17:42
Next major version I guess 4.3

**Comment by damianszczepanik** [comment] 2019-01-20 20:11
Support for this problem will be delivered with next release.
