### ISSUE TITLE
CannotResolveClassException: CucumberReportBuildAction

### ISSUE THREAD

**Issue by lemrouch** [jenkinsci/cucumber-reports-plugin#74] opened 2016-08-02 12:28 UTC
Hi,
we tried to upgrade cucumber-report-plugin from 2.2.0 to 2.6.3 and we ended with CannotResolveClassException: CucumberReportBuildAction in our old builds and the Cucumber-JVM reports link was not working.
Downgrade of the plugin fixed it.
There was nothing in the jenkins log.
Does anybody have idea where might be the problem or how to debug jenkins classloader?

**Comment by lemrouch** [comment] 2016-08-02 14:56
I tried to install the latest working version and it's fine up to 2.5.1.
Version 2.6.0 is the first one which is not working.

**Comment by lemrouch** [comment] 2016-08-02 15:15
In the XML files of old builds is
<net.masterthought.jenkins.CucumberReportBuildAction plugin="cucumber-reports@2.2.0">
and I can see in
https://github.com/jenkinsci/cucumber-reports-plugin/compare/cucumber-reports-2.5.1...cucumber-reports-2.6.0
that the
src/main/java/net/masterthought/jenkins/CucumberReportBuildAction.java has been removed.
How can I fix this?

**Comment by damianszczepanik** [comment] 2016-08-02 18:05
Problem with Jenkins compatibility?  I have tested with the most recent version but also with older installations.

**Comment by lemrouch** [comment] 2016-08-03 07:48
Hi,
to be clear:
fresh build with 2.6.3 plugin has working report.
But I just can't see reports from builds done with plugin 2.5.1 or older.
Can you try to downgrade plugin to 2.5.1, run build, upgrade plugin to 2.6.3 and confirm you can see the report please?
I think cucumber-reports-plugin is not backward compatible.

We have latest Jenking debian package from official repository.

**Comment by lemrouch** [comment] 2016-08-03 07:50
The exception can bee seen in jeninks web /administrativeMonitor/OldData/manage

Unreadable Data

It is acceptable to leave unreadable data in these files, as Jenkins will safely ignore it. To avoid the log messages at Jenkins startup you can permanently delete the unreadable data by resaving these files using the button below.
Type	Name	Error
hudson.model.FreeStyleBuild	features-tests #3125	CannotResolveClassException: net.masterthought.jenkins.CucumberReportBuildAction

**Comment by lemrouch** [comment] 2016-08-03 07:57
And strange thing:
I reverted back from 2.6.3 to 2.5.1 and I can see the latest report but old reports are not available.

**Comment by damianszczepanik** [comment] 2016-08-03 17:42
Duplicate of damianszczepanik/cucumber-reporting-jenkins#162

**Comment by lemrouch** [comment] 2016-08-04 11:05
Ah, sorry. I missed the #162 bug.
Feel free to close this one as well. Or keep it open so others won't open any more duplicates.
Thanks for your time and effort!

**Closed** 2016-08-25 19:46 UTC
