### ISSUE TITLE
NullPointerException when running cucumber reports

### ISSUE THREAD

**Issue by ctaclas** [jenkinsci/cucumber-reports-plugin#120] opened 2017-02-16 18:55 UTC
We recently upgraded to version 3.5.0 of the cucumber reports plugin. I believe we may have previously been at 3.4.0, but I'm not 100% sure. After this upgrade, our jenkins jobs began failing when processing the reports.

We are using cucumber gem v2.0.0, ruby 2.3.1 to run the tests. I have attached the JSON report files in a zip. I believe there is a difference in the JSON format between cucumber 2.0 and more recent versions of cucumber, but I'm not sure if that is the issue here.

Jenkins version is 2.32.2

Here is an excerpt from the job log:

[CucumberReport] Preparing Cucumber Reports
[CucumberReport] Copied 7 json files from workspace "/var/lib/jenkins/workspace/Mob_Core_iOS_Test_Smoke/cucumber_appium/test_results" to reports directory "/var/lib/jenkins/jobs/Mob_Core_iOS_Test_Smoke/builds/2400/cucumber-html-reports/.cache"
[CucumberReport] Filtered out 7 json files:
[CucumberReport] /var/lib/jenkins/jobs/Mob_Core_iOS_Test_Smoke/builds/2400/cucumber-html-reports/.cache/results-.json
[CucumberReport] /var/lib/jenkins/jobs/Mob_Core_iOS_Test_Smoke/builds/2400/cucumber-html-reports/.cache/results-2.json
[CucumberReport] /var/lib/jenkins/jobs/Mob_Core_iOS_Test_Smoke/builds/2400/cucumber-html-reports/.cache/results-3.json
[CucumberReport] /var/lib/jenkins/jobs/Mob_Core_iOS_Test_Smoke/builds/2400/cucumber-html-reports/.cache/results-4.json
[CucumberReport] /var/lib/jenkins/jobs/Mob_Core_iOS_Test_Smoke/builds/2400/cucumber-html-reports/.cache/results-5.json
[CucumberReport] /var/lib/jenkins/jobs/Mob_Core_iOS_Test_Smoke/builds/2400/cucumber-html-reports/.cache/results-6.json
[CucumberReport] /var/lib/jenkins/jobs/Mob_Core_iOS_Test_Smoke/builds/2400/cucumber-html-reports/.cache/results-7.json
ERROR: Build step failed with exception
java.lang.NullPointerException
	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:133)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:86)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1753)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
Build step 'Cucumber reports' marked build as failure

[archive.zip](https://github.com/jenkinsci/cucumber-reports-plugin/files/781176/archive.zip)

**Comment by damianszczepanik** [comment] 2017-02-16 21:27
Duplicate of https://github.com/jenkinsci/cucumber-reports-plugin/issues/119

**Comment by damianszczepanik** [comment] 2017-02-17 20:33
Released

**Comment by ctaclas** [comment] 2017-02-17 21:15
Fantastic, thank you @damianszczepanik and team for the quick turnaround!

**Closed** 2017-02-20 22:40 UTC
