### ISSUE TITLE
Duplicate reports when calling pipeline step twice for buildStatus

### ISSUE THREAD

**Issue by nicodn** [jenkinsci/cucumber-reports-plugin#370] opened 2020-08-06 21:49 UTC
## Summary:

After the latest update we're getting duplicate cucumber reports due to the way we use the `buildStatus` feature.

## Details:

We call the cucumber step twice in our pipeline because we have different criteria for setting `buildStatus` to `UNSTABLE` or `FAILURE` depending on the test results. Eg:

```
    cucumber buildStatus: 'FAILURE', // criteria for Failure status
            failedScenariosPercentage: 99.0, // <- fail if all scenarios fail
            skippedStepsPercentage: 99.0, // <- fail if all steps are skipped
            ...

    cucumber buildStatus: 'UNSTABLE', // criteria for Unstable status            
            failedStepsNumber: 1, // <- unstable if a single step fails
            ...
```
We _do not_ set any `reportTitle`.

After we upgraded to version 5.3.0 which includes https://github.com/jenkinsci/cucumber-reports-plugin/pull/344, we are now seeing duplicate cucumber report links in the sidebar:
![Screen Shot 2020-08-06 at 5 33 19 PM](https://user-images.githubusercontent.com/24900139/89584951-f599ee80-d80a-11ea-99ef-3aa76a8139f3.png)

How can we achieve the desired behaviour without the duplicate links? Thanks!!

**Comment by damianszczepanik** [comment] 2020-08-09 10:10
Looks like duplicate of #365

**Comment by damianszczepanik** [comment] 2020-08-09 11:24
Is it really duplicate ?
Add
``reportTitle: 'report name'``
to each and check again

**Closed** 2020-08-15 14:00 UTC
