### ISSUE TITLE
Is it possible to mark skipped/ignored tests as skipped or ignored in the report instead of failed?

### ISSUE THREAD

**Issue by NikolayStanoev** [jenkinsci/cucumber-reports-plugin#303] opened 2019-02-28 20:41 UTC
In cucumber-jvm there is a support for TestNG SkipException since version 3.0.0 - https://github.com/cucumber/cucumber-jvm/blob/master/CHANGELOG.md

Currently, all tests which throw SkipException are market as failed. It is possible to check for such exceptions and instead of marking the test as failed to mark it as ignored or skipped.

For example - html plugin in cucumber marks such tests as ignored / skipped (with blue lines) instead of failed.

**Comment by damianszczepanik** [comment] 2019-03-01 21:52
Can you link specification so I know how it work?

**Comment by NikolayStanoev** [comment] 2019-03-02 09:50
https://github.com/cucumber/cucumber-jvm/blob/master/CHANGELOG.md

Check 3.0.0 release notes - this is the PR - https://github.com/cucumber/cucumber-jvm/pull/1338

As an idea there could be an option in the report configuration whether such tests to be displayed or not in the report. 

The fix which i have locally is just checking the output json file and if scenario has SkipException then i just remove it from elements list.

**Comment by damianszczepanik** [comment] 2019-03-02 15:14
I can't see any sample reference how the new JSON should look like

**Comment by NikolayStanoev** [comment] 2019-03-02 21:41
I will provide such example on Thursday.

**Comment by NikolayStanoev** [comment] 2019-03-07 13:32
Hi @damianszczepanik ,

I could not find a json spec for SkipException in cucumber code.

However, you can see [output example](https://1drv.ms/u/s!Ar4NHmgENqzmg20qv-due3OM7mIQ) for a test which is Scenario Outline where only one of the examples is executed and rest of them are skipped. In the example above the SkipException is thrown in the the HOOK but there is a way to send such exception in the test steps as well. The result is almost the same. There is an **error_message** key which starts with **org.testng.SkipException**. 

I hope this can help.

**Comment by damianszczepanik** [comment] 2019-03-07 17:05
Step should be marked as ignored but scenario and features are marked as failed. And thus us by design.

**Comment by damianszczepanik** [comment] 2020-01-04 21:24
Lack of requirements

**Closed by damianszczepanik** 2020-01-04 21:24 UTC
