### ISSUE TITLE
cucumber-jvm reports are not showing the latest results

### ISSUE THREAD

**Issue by udayanem** [jenkinsci/cucumber-reports-plugin#75] opened 2016-08-10 04:19 UTC
I am not getting the latest test results in Cucumber-jvm reports. Previous execution results was shown.
Cucumber-jvm reports version: 2.6.3
Below is my Cucumber runner file,
@RunWith(Cucumber.class)
@CucumberOptions(
features="classpath:",
glue=
{"stepdefinitions","helpers"}
,
//	plugin =
{"pretty", "html:target/cucumber","json:target/cucumber.json"}
,
plugin =
{"pretty", "json:target/cucumber.json"}
,
tags=
{"@RegistrationForm"}
)
public class Runnertest 
{
}
Attachment containing the actual json file created.
But you could see two feature files are executed, though i have configured only one feature in above.
![jenkins](https://cloud.githubusercontent.com/assets/10852370/17541703/91058c34-5edf-11e6-888d-face2be8d033.png)
[cucumber.txt](https://github.com/jenkinsci/cucumber-reports-plugin/files/410313/cucumber.txt)

**Comment by damianszczepanik** [comment] 2016-08-10 17:58
Duplicate of damianszczepanik/cucumber-reporting/issues/508

**Closed by damianszczepanik** 2016-08-10 17:58 UTC
